export enum ACTIONS {
  ADD_SECTION = "ADD SECTION",
  EDIT_SECTION = "EDIT SECTION",
  DELETE_SECTION = "DELETE SECTION",
  SELECT_SECTION = "SELECT SECTION",
  EDITOR_STATE_CHANGE = "EDITOR STATE CHANGE",
  SET_INIITAL_DATA = "SET INIITAL DATA",
  SET_DEFAULT_MENUS = "SET DEFAULT MENUS",
}
