export enum ACTIONS {
  ADD_SECTION = "ADD SECTION",
  EDIT_SECTION = "EDIT SECTION",
  DELETE_SECTION = "DELETE SECTION",
  SELECT_SECTION = "SELECT SECTION",
  EDITOR_STATE_CHANGE = "EDITOR STATE CHANGE",
}
